### ISSUE TITLE
[Feature] 마이페이지 > 내 정보 수정 : 이미지 형식 수정

### ISSUE THREAD

**Issue by dkin12** [Dont-forget6/Dont-Forget#1]
## ✅ Description
마이페이지> 내 정보 수정에서 이미지 형식을 수정
이미지 형식을 둥근 형태로 바꾸고, 빠르게 불러와 로딩 시간을 단축 시킬 것
내 정보에서 이름을 수정하면 다른 쪽에서도 이름이 다 수정되게 바꿀 것 

## ✔️ TODO
- [x] 이미지 형식 둥근 형태로 수정
- [x] 이미지 로딩 시간 단축 ( 코루틴 사용예정 ) 
- [x] 내 정보 수정 이름 수정 추가

**Comment by dkin12** [comment]
[design] 프로필 원형 이미지로 변경
회원가입, 마이페이지, 친구 화면 이미지 원형으로 변경
Fixes: #1
