### ISSUE TITLE
[Feature] 홈화면 > 커스텀 캘린더 및 할 일 수정

### ISSUE THREAD

**Issue by dlwngud** [Dont-forget6/Dont-Forget#3]
## ✅ Description
위치가 없으면 Gone하고 커스텀 캘린더로 사이즈가 변경이 가능하고 오늘 날짜 선택 버튼 만들기

## ✔️ TODO
- [x] 홈화면에서 위치 없으면 GONE처리 
- [ ] 홈화면 커스텀 캘린더 및 사이즈 변경가능한느낌으로
- [ ] 홈화면 캘린더 작게
- [ ] 홈화면에서 오늘 날짜 선택가능
